# Generated by Django 5.0.6 on 2024-07-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeFirstName', models.CharField(default='', max_length=50)),
                ('employeeLastName', models.CharField(default='', max_length=50)),
                ('employeeEmail', models.CharField(default='', max_length=100)),
                ('employeePhone', models.CharField(default='', max_length=15)),
                ('employeeAddress', models.CharField(default='', max_length=100)),
                ('employeeCity', models.CharField(default='', max_length=50)),
                ('employeeState', models.CharField(default='', max_length=50)),
                ('employeeZip', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='N/A', max_length=100)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('miles', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.carcolor')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.carmodel')),
            ],
        ),
    ]
