# Generated by Django 5.0.6 on 2024-07-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='lastName',
        ),
        migrations.AddField(
            model_name='customers',
            name='customerAddress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='customerCity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customers',
            name='customerEmail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='customerFirstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customers',
            name='customerLastName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customers',
            name='customerPhone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='customers',
            name='customerState',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customers',
            name='customerZip',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='carcolor',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='make',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
