# Generated by Django 5.0.6 on 2024-07-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_customers_firstname_remove_customers_lastname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customers',
            new_name='customer',
        ),
    ]
