# Generated by Django 5.0.6 on 2024-07-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_customers_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employeeAddress',
            field=models.CharField(default='Unknown Address', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='employeeCity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employees',
            name='employeeEmail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='employeePhone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='employees',
            name='employeeState',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employees',
            name='employeeZip',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeFirstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeLastName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
