# Generated by Django 5.0.6 on 2024-07-06 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_employees_employeeaddress_employees_employeecity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cars',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='name',
        ),
        migrations.AddField(
            model_name='cars',
            name='CarYear',
            field=models.IntegerField(default='N/A'),
        ),
        migrations.AddField(
            model_name='cars',
            name='Miles',
            field=models.IntegerField(default='N/A'),
        ),
        migrations.AddField(
            model_name='cars',
            name='Price',
            field=models.IntegerField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeAddress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cars',
            name='CarColor',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='homepage.carcolor'),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='N/A', max_length=100)),
                ('make', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='homepage.carmake')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='CarModel',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='homepage.carmodel'),
        ),
    ]
