# Generated by Django 5.0.6 on 2024-07-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_carcolor_carmake_remove_cars_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='CarYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Miles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
