# Generated by Django 5.0.6 on 2024-07-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_cars_caryear_alter_cars_miles_alter_cars_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carcolor',
            old_name='model',
            new_name='CarColor',
        ),
    ]
