# Generated by Django 5.0.6 on 2024-07-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_rename_model_carcolor_carcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='CarYear',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Miles',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Price',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
