# Generated by Django 5.0.6 on 2024-07-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_cars_caryear_alter_cars_miles_alter_cars_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='CarYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Miles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
